# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mhw4DYtu_FUGnBERwbQaVfQa3Qpy95sa
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
#data uploaded
df = pd.read_csv("Heart_Disease_Prediction.csv")
df.head()

df = pd.read_csv("Heart_Disease_Prediction.csv")
df.columns
df["Heart Disease"].unique()
df.columns = df.columns.str.replace(" ", "_")
df.columns
df.head()

df["Heart_Disease"].unique()
df["Heart_Disease"] = df["Heart_Disease"].map({
    "Presence": 1,
    "Absence": 0
})
df.columns
df.head()

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
df.head()

X = df.drop("Heart_Disease", axis=1)
y = df["Heart_Disease"]
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
df.head()

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

X = df.drop("Heart_Disease", axis=1)
y = df["Heart_Disease"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = LinearRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)

print("R2 Score:", r2_score(y_test, predictions))

from sklearn.model_selection import train_test_split

X = df.drop("Heart_Disease", axis=1)
y = df["Heart_Disease"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

ConfusionMatrixDisplay.from_predictions(y_test, y_pred)
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# scikit-learn
# pandas
# numpy
# matplotlib
#



!ls

from google.colab import files

files.download("scaler.pkl")
files.download("requirements.txt")